### ISSUE TITLE
how to inference an image?

### ISSUE THREAD

**Issue by IvyGongoogle** [davidsandberg/facenet#186]
new to face recognition. Now I just want to inference an image, but I do not know run which py script in this repository. 
Looking forward to your reply.
Thank you in advance.

**Comment by davidsandberg** [comment]
The script `compare.py` will calculate the embeddings for a few images and that is one way to run inference.

**Comment by RakshakTalwar** [comment]
@IvyGongoogle you can try the batch_represent.py script that I recently contributed.

It's under the tmp/ directory

**Comment by IvyGongoogle** [comment]
@davidsandberg @RakshakTalwar  Thank you very much!

**Comment by AKSHAYUBHAT** [comment]
@RakshakTalwar @davidsandberg   I am trying to do inference on set of images using your script to incorporate facenet into [Deep Video Analytics](https://github.com/AKSHAYUBHAT/DeepVideoAnalytics). However  it require pre-detected / cropped faces. I saw that there is an "align module" that uses MTCNN ported to tensorflow. Is it ready to use? And is there any test script demonstrating how to use it?
Thanks,

**Comment by RakshakTalwar** [comment]
@AKSHAYUBHAT you would use the following script to detect and align using MTCNN, then you can run it through batch-represent

https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py

**Comment by IvyGongoogle** [comment]
@davidsandberg @RakshakTalwar  when I run the script `batch_represent.py`, it shows error
`
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 8 I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 8 Loading trained model...  Traceback (most recent call last):   File "batch_represent.py", line 148, in <module>     main(parse_arguments(sys.argv[1:]))   File "batch_represent.py", line 95, in main     facenet.load_model(args.trained_model_dir, meta_file, ckpt_file)   File "../src/facenet.py", line 368, in load_model     saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file)) AttributeError: 'module' object has no attribute 'import_meta_graph'`

This problem seems to be about tensorflow.  How to solve this problem? 
I use tf0.5. Do I have to use tf1.0?  

Thank you very much.

**Comment by IvyGongoogle** [comment]
Now I use tf0.9, but it shows error:
`Segmentation fault (core dumped)`
it seems to be a hidden error.
Do I have to use tf1.0?

**Comment by IvyGongoogle** [comment]
@davidsandberg  @RakshakTalwar

**Comment by RakshakTalwar** [comment]
@IvyGongoogle I was able to get it to work with tf0.12 as well, not sure if it'll work with 0.9

**Comment by AKSHAYUBHAT** [comment]
It works correctly with tf 1.0. One issue is that there is no way to set GPU memory percentage, I modified the script while incorporating. You can do something like this 

```
        gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.15)
        sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False))
        with sess.as_default():

```

**Comment by pandearti** [comment]
Hi @davidsandberg @RakshakTalwar 
- which script has the infer function that will identify the class of given input image?
- I tried compare.py, it only outputs the distances between given input images. Does not identify the class (person name in this case)
- even if I use batch_generate.py, I will eventually need to call infer function for classification.

**Comment by IvyGongoogle** [comment]
@davidsandberg @RakshakTalwar  I also need the script as @pandearti said above.

**Comment by davidsandberg** [comment]
I have added a script 'classifier.py' that can train a small classifier on the facenet features. There is also a wiki page showing how to use it. Hopefully that will help.

**Comment by IvyGongoogle** [comment]
@davidsandberg  thank you very much!
